[package]
name = "htx"
version = "0.1.0"
authors = ["Mack Straight <mack@discordapp.com>"]
description = "htx"
license = "GPL-3.0-or-later"
edition = "2018"
repository = "https://github.com/eiz/htx"

[dependencies]
